Core module.
Classes
class ExceptionDescriptor
Exception class. More...
class ImageFrame
Image frame wrapper class. More...
class LocalSettings
Singleton settings manager class. More...
class Mutex
A synchronization primitive that can also be used for interprocess synchronization. More...
class Runnable
Abstract interface for runnable objects. More...
class Thread
Abstract class for handling threads. More...
class Visualizer
Singleton window and image display manager class. More...
Detailed Description
Class Documentation
class ExceptionDescriptor
Exception class.
Exception class whose instances store an error message, source file, function and line number.
Public Member Functions
ExceptionDescriptor (const std::string &error, const std::string &fileName, const std::string &funcName, int line, bool isError=true) throw ()
Constructor.
ExceptionDescriptor (const ExceptionDescriptor &e) throw ()
Copy constructor.
~ExceptionDescriptor (void) throw ()
Destructor.
void TraceError (void) throw ()
Write the exception description to stderr.
const char * what (void) const throw ()
std::exception::what()
Private Attributes
std::string error_
Error message.
std::string fileName_
Name of the file.
std::string funcName_
Name of the function.
bool isError_
Error or abnormal operation.
int line_
Line number.
Constructor & Destructor Documentation
ExceptionDescriptor::ExceptionDescriptor (const std::string & error, const std::string & fileName, const std::string & funcName, int line, bool isError = true) throw ()
Constructor.
Parameters
error Error message.
fileName Name of the file in which the exception was raised.
funcName Name of the function in which the exception was raised.
line Number of line on which the exception was raised.
isError Error or abnormal operation.
Should be used through the macro NewError(message) or NewWarning(message).
ExceptionDescriptor::ExceptionDescriptor (const ExceptionDescriptor & e) throw ()
Copy constructor.
Parameters
e Another ExceptionDescriptor.
ExceptionDescriptor::~ExceptionDescriptor (void) throw ()
Destructor.
Member Function Documentation
void ExceptionDescriptor::TraceError (void) throw ()
Write the exception description to stderr.
Referenced by main().
const char * ExceptionDescriptor::what (void) const throw ()
std::exception::what()
Member Data Documentation
std::string ExceptionDescriptor::error_ [private]
Error message.
std::string ExceptionDescriptor::fileName_ [private]
Name of the file.
std::string ExceptionDescriptor::funcName_ [private]
Name of the function.
bool ExceptionDescriptor::isError_ [private]
Error or abnormal operation.
int ExceptionDescriptor::line_ [private]
Line number.
class ImageFrame
Image frame wrapper class.
Gets image frames as cv::Mat objects.
Public Member Functions
ImageFrame (int cameraId)
Constructor.
ImageFrame (const std::string &imageName)
Constructor.
~ImageFrame (void)
Destructor.
const cv::Mat & GetFrame (void)
Gets a frame from somewhere.
Private Attributes
cv::VideoCapture cap_
Temporary capture for getting frame.
cv::Mat frame_
Loaded or captured image.
Constructor & Destructor Documentation
ImageFrame::ImageFrame (int cameraId = 0)
Constructor.
Parameters
cameraId ID of the camera.
References ExceptionError.
ImageFrame::ImageFrame (const std::string & imageName)
Constructor.
Parameters
imageName Name of the image, which from the features will be extracted.
ImageFrame::~ImageFrame (void)
Destructor.
Member Function Documentation
const Mat & ImageFrame::GetFrame (void)
Gets a frame from somewhere.
Returns
frame Output argument for the frame.
References ExceptionError.
Referenced by HuroAlgorithm::Process().
Member Data Documentation
cv::VideoCapture ImageFrame::cap_ [private]
Temporary capture for getting frame.
cv::Mat ImageFrame::frame_ [private]
Loaded or captured image.
class LocalSettings
Singleton settings manager class.
Contains the paths of XMLs and video files.
Public Member Functions
std::string GetDataDirectory (void) const
Data directory getter.
std::string GetImageDirectory (void) const
Image directory getter.
std::string GetProcessXmlFileName (void) const
Process xml filename getter.
std::string GetSettingsDirectory (void) const
Settings directory getter.
Static Public Member Functions
static LocalSettings * GetInstance (void)
Instance getter.
Private Member Functions
LocalSettings (void)
Constructor.
~LocalSettings (void)
Destructor.
Private Attributes
std::string dataDirectory_
Data directory root.
std::string imageDirectory_
Image directory root.
std::string processXmlFileName_
The configuration file.
std::string settingsDirectory_
Settings directory root.
Constructor & Destructor Documentation
LocalSettings::LocalSettings (void) [private]
Constructor.
References ExceptionError.
LocalSettings::~LocalSettings (void) [private]
Destructor.
Member Function Documentation
string LocalSettings::GetDataDirectory (void) const
Data directory getter.
Returns
Data directory root.
string LocalSettings::GetImageDirectory (void) const
Image directory getter.
Returns
Settings directory root.
LocalSettings * LocalSettings::GetInstance (void) [static]
Instance getter.
Returns
The instance.
string LocalSettings::GetProcessXmlFileName (void) const
Process xml filename getter.
Returns
Settings directory root.
string LocalSettings::GetSettingsDirectory (void) const
Settings directory getter.
Returns
Settings directory root.
Member Data Documentation
std::string LocalSettings::dataDirectory_ [private]
Data directory root.
std::string LocalSettings::imageDirectory_ [private]
Image directory root.
std::string LocalSettings::processXmlFileName_ [private]
The configuration file.
std::string LocalSettings::settingsDirectory_ [private]
Settings directory root.
class Mutex
A synchronization primitive that can also be used for interprocess synchronization.
When two or more threads need to access a shared resource at the same time, the system needs a synchronization mechanism to ensure that only one thread at a time uses the resource. Mutex is a synchronization primitive that grants exclusive access to the shared resource to only one thread.
Public Member Functions
Mutex (void)
Constructor.
~Mutex (void)
Destructor.
void Lock (void)
Blocks the current thread.
void Unlock (void)
Unblocks the current thread.
Private Attributes
pthread_mutex_t mutex_
Inner mutex object.
Constructor & Destructor Documentation
Mutex::Mutex (void)
Constructor.
References mutex_.
Mutex::~Mutex (void)
Destructor.
References mutex_.
Member Function Documentation
void Mutex::Lock (void)
Blocks the current thread.
References mutex_.
void Mutex::Unlock (void)
Unblocks the current thread.
References mutex_.
Member Data Documentation
pthread_mutex_t Mutex::mutex_ [private]
Inner mutex object.
Referenced by Lock(), Mutex(), Unlock(), and ~Mutex().
class Runnable
Abstract interface for runnable objects.
Public Member Functions
virtual ~Runnable (void)=0
Destructor.
virtual void * Run (void)=0
Pure virtual thread main.
Constructor & Destructor Documentation
Runnable::~Runnable (void) [pure virtual]
Destructor.
Member Function Documentation
virtual void* Runnable::Run (void) [pure virtual]
Pure virtual thread main.
class Thread
Abstract class for handling threads.
Runnable classes can be derived from this class.
Threads can be started and stopped with the Start() and Join() methods respectively. The new thread will enter the implemented Run() method.
Public Member Functions
Thread (std::auto_ptr< Runnable > run, bool isDetached=false)
Constructor.
Thread (bool isDetached=false)
Constructor.
virtual ~Thread (void)
Destructor.
void * Join (void)
void Start (void)
Starts the thread.
Private Member Functions
virtual void * Run (void)=0
Pure virtual thread main.
void SetCompleted (void)
Static Private Member Functions
static void * StartThread (void *pVoid)
Thread start function when no Runnable is involved.
static void * StartThreadRunnable (void *pVoid)
Thread start function when a Runnable is involved.
Private Attributes
bool detached_
void * result_
std::auto_ptr< Runnable > runnable_
pthread_attr_t threadAttribute_
pthread_t threadID_
Constructor & Destructor Documentation
Thread::Thread (std::auto_ptr< Runnable > run, bool isDetached = false)
Constructor.
Parameters
run Runnable object.
isDetached Whether or not the thread is to be created in a detached state.
Thread::Thread (bool isDetached = false)
Constructor.
Parameters
isDetached Whether or not the thread is to be created in a detached state.
Thread::~Thread (void) [virtual]
Destructor.
Member Function Documentation
void * Thread::Join (void)
References ExceptionError, result_, and threadID_.
virtual void* Thread::Run (void) [private], [pure virtual]
Pure virtual thread main.
Implemented in LocalFeature, and GlobalFeature.
Referenced by StartThread().
void Thread::SetCompleted (void) [private]
Referenced by StartThread(), and StartThreadRunnable().
void Thread::Start (void)
Starts the thread.
References detached_, ExceptionError, runnable_, StartThread(), StartThreadRunnable(), threadAttribute_, and threadID_.
void * Thread::StartThread (void * pVoid) [static], [private]
Thread start function when no Runnable is involved.
Parameters
pVoid
References result_, Run(), and SetCompleted().
Referenced by Start().
void * Thread::StartThreadRunnable (void * pVoid) [static], [private]
Thread start function when a Runnable is involved.
Parameters
pVoid
References result_, runnable_, and SetCompleted().
Referenced by Start().
Member Data Documentation
bool Thread::detached_ [private]
Referenced by Start().
void* Thread::result_ [private]
Referenced by Join(), StartThread(), and StartThreadRunnable().
std::auto_ptr<Runnable> Thread::runnable_ [private]
Referenced by Start(), and StartThreadRunnable().
pthread_attr_t Thread::threadAttribute_ [private]
Referenced by Start().
pthread_t Thread::threadID_ [private]
Referenced by Join(), and Start().
class Visualizer
Singleton window and image display manager class.
Public Member Functions
void PutText (cv::Mat &image, const std::string &text, cv::Point &org)
Renders the specified text string in the image.
void SetTextProperties (int fontFace, double fontScale, cv::Scalar fontColor, int fontThickness)
Sets the text's properties.
void ShowImage (const std::string &name, const cv::Mat &image, bool waitForKey=true)
Creates a window and show an image within it.
Static Public Member Functions
static Visualizer * GetInstance (void)
Instance getter.
Private Member Functions
Visualizer (void)
Constructor.
~Visualizer (void)
Destructor.
Private Attributes
cv::Scalar fontColor_
Text color.
int fontFace_
Font type.
double fontScale_
Font scale factor that is multiplied by the font-specific base size.
int fontThickness_
Thickness of the lines used to draw a text.
Constructor & Destructor Documentation
Visualizer::Visualizer (void) [private]
Constructor.
Referenced by GetInstance().
Visualizer::~Visualizer (void) [private]
Destructor.
Member Function Documentation
Visualizer * Visualizer::GetInstance (void) [static]
Instance getter.
Returns
The instance.
References Visualizer().
void Visualizer::PutText (cv::Mat & image, const std::string & text, cv::Point & org)
Renders the specified text string in the image.
Parameters
image Image.
text Text string to be drawn.
org Bottom-left corner of the text string in the image.
References fontColor_, fontFace_, fontScale_, and fontThickness_.
void Visualizer::SetTextProperties (int fontFace, double fontScale, cv::Scalar fontColor, int fontThickness)
Sets the text's properties.
Parameters
fontFace Font type.
fontScale Font scale factor that is multiplied by the font-specific base size.
fontColor Text color.
fontThickness Thickness of the lines used to draw a text.
References fontColor_, fontFace_, fontScale_, and fontThickness_.
void Visualizer::ShowImage (const std::string & name, const cv::Mat & image, bool waitForKey = true)
Creates a window and show an image within it.
Parameters
name Name of the window.
image Image to be shown.
waitForKey Waits for a pressed key.
Member Data Documentation
cv::Scalar Visualizer::fontColor_ [private]
Text color.
Referenced by PutText(), and SetTextProperties().
int Visualizer::fontFace_ [private]
Font type.
Referenced by PutText(), and SetTextProperties().
double Visualizer::fontScale_ [private]
Font scale factor that is multiplied by the font-specific base size.
Referenced by PutText(), and SetTextProperties().
int Visualizer::fontThickness_ [private]
Thickness of the lines used to draw a text.
Referenced by PutText(), and SetTextProperties().