var files =
[
    [ "Core/include/ExceptionDescriptor.h", "_exception_descriptor_8h.html", "_exception_descriptor_8h" ],
    [ "Core/include/ImageFrame.h", "_image_frame_8h.html", null ],
    [ "Core/include/LocalSettings.h", "_local_settings_8h.html", null ],
    [ "Core/include/Mutex.h", "_mutex_8h.html", null ],
    [ "Core/include/Runnable.h", "_runnable_8h.html", null ],
    [ "Core/include/Thread.h", "_thread_8h.html", null ],
    [ "Core/src/ExceptionDescriptor.cpp", "_exception_descriptor_8cpp.html", null ],
    [ "Core/src/ImageFrame.cpp", "_image_frame_8cpp.html", null ],
    [ "Core/src/LocalSettings.cpp", "_local_settings_8cpp.html", null ],
    [ "Core/src/Mutex.cpp", "_mutex_8cpp.html", null ],
    [ "Core/src/Runnable.cpp", "_runnable_8cpp.html", null ],
    [ "Core/src/Thread.cpp", "_thread_8cpp.html", null ],
    [ "FeatureExtractor/include/Feature.h", "_feature_8h.html", null ],
    [ "FeatureExtractor/include/OrbFeature.h", "_orb_feature_8h.html", null ],
    [ "FeatureExtractor/include/SiftFeature.h", "_sift_feature_8h.html", null ],
    [ "FeatureExtractor/include/StarFeature.h", "_star_feature_8h.html", null ],
    [ "FeatureExtractor/include/SurfFeature.h", "_surf_feature_8h.html", null ],
    [ "FeatureExtractor/src/Feature.cpp", "_feature_8cpp.html", null ],
    [ "FeatureExtractor/src/OrbFeature.cpp", "_orb_feature_8cpp.html", null ],
    [ "FeatureExtractor/src/SiftFeature.cpp", "_sift_feature_8cpp.html", null ],
    [ "FeatureExtractor/src/StarFeature.cpp", "_star_feature_8cpp.html", null ],
    [ "FeatureExtractor/src/SurfFeature.cpp", "_surf_feature_8cpp.html", null ],
    [ "ObjectRecognition/include/ObjRecAlgorithm.h", "_obj_rec_algorithm_8h.html", null ],
    [ "ObjectRecognition/src/Main.cpp", "_main_8cpp.html", "_main_8cpp" ],
    [ "ObjectRecognition/src/ObjRecAlgorithm.cpp", "_obj_rec_algorithm_8cpp.html", null ]
];